[package]
name = "clean-backup-files"
version = "0.1.0"
authors = ["Alex Hill <alexander.d.hill.89@gmail.com>"]
license = "MIT"

[dependencies]
walkdir = "0.1"
regex = "0.1"
env_logger = "0.3"
log = "0.3"
